### ISSUE TITLE
Bug: Start tag expected, '<' not found

### ISSUE THREAD

**Issue by shohei-doi** [amatsuo/kaigiroku#2]
Thank you for such a nice package. When I tried to download the speeches in Houmu iinkai of Upper House in 1949, I encountered the following error:
```
libtary(tidyverse)
library(kaigiroku)
temp <- get_meeting(meetingName = "法務", year = 1949)

60 records found
Fetching (current_record_position: 1)
...
Fetching (current_record_position: 29)

Start tag expected, '<' not found
Error: 1: Start tag expected, '<' not found
```

**Comment by amatsuo** [comment]
Hello. Thank you for using my package.

I actually was able to reproduce the error. 

It seems that the problem is the slow server response (and impatience of `xmlParse()` which is used internally). I updated the package handling with this issue by switching to locally downloading files when an error occurred. 

Please install a newer version and try.

**Comment by amatsuo** [comment]
Hi @shohei-doi 

I made a further update on the package and it is more robust against the download failure. If you are still interested in using the package, install the latest master.

**Comment by shohei-doi** [comment]
I appreciate your kind response and feel sorry for delaying my replay. Your updated package avoids the error but does not work for me due to another error. So, I opened a new issue #5 and I would be grateful if you could fix it.
